#pragma once

#define WINDOW_HEIGHT 800.0f
#define WINDOW_WIDTH 1200.0f

#define BALL_RADIUS 15
#define HORIZONTAL_VELOCITY 2.0f
#define VERTICAL_VELOCITY 2.0f
#define HORIZONTAL_POSITION 585.0f

#define PADDLE_HEIGHT 20.0f
#define PADDLE_WIDTH 250.0f
#define DISTANCE 10.0f

#define BRICK_HEIGHT 20.0f
#define BRICK_WIDTH 50.0f

#define BRICK_COUNT_PER_LAYER 24 
#define LAYER_COUNT 3
